select
sc.name
, sc.id
, sc.academic_period
, sc.course_identification
, SC.FINAL_GRADE
, SC.PERSON_UID

from student_course sc

where sc.final_grade is not null
--and sc.academic_Period >= '201835'
--AND SC.FINAL_GRADE NOT LIKE '%T%'
and course_identification in ('MATH141','MATH114','MTHD106')

and (exists (select 'X'

from student_course sc2

WHERE SC2.COURSE_IDENTIFICATION = 'MATH141'

--AND (SC2.FINAL_GRADE NOT LIKE '%T%' AND SC2.FINAL_GRADE NOT LIKE '%W%' AND SC2.FINAL_GRADE NOT LIKE '%N%' AND SC2.FINAL_GRADE NOT LIKE '%F%' 
--AND SC2.FINAL_GRADE NOT LIKE '%D%' AND SC2.FINAL_GRADE NOT LIKE '%C-%' AND SC2.FINAL_GRADE NOT LIKE '%P%')
--AND (SC2.FINAL_GRADE >= 'C' OR SC2.FINAL_GRADE >= '(2.0)')
--AND SC2.ACADEMIC_PERIOD >= '201835'
AND SC2.PERSON_UID = SC.PERSON_UID
AND SC2.FINAL_GRADE IS NOT NULL))

and (exists (select 'X'

from student_course sc3

WHERE SC3.COURSE_IDENTIFICATION = 'MTHD106'

--AND (SC3.FINAL_GRADE NOT LIKE '%T%' AND SC3.FINAL_GRADE NOT LIKE '%W%' AND SC3.FINAL_GRADE NOT LIKE '%N%' AND SC3.FINAL_GRADE NOT LIKE '%F%' 
--AND SC3.FINAL_GRADE NOT LIKE '%D%' AND SC3.FINAL_GRADE NOT LIKE '%C-%' AND SC3.FINAL_GRADE NOT LIKE '%P%')
--AND (SC3.FINAL_GRADE >= 'C' OR SC3.FINAL_GRADE >= '(2.0)')
--AND SC2.ACADEMIC_PERIOD >= '201835'
AND SC3.PERSON_UID = SC.PERSON_UID
AND SC3.FINAL_GRADE IS NOT NULL)) 


and (exists (select 'X'

from student_course sc4

WHERE SC4.COURSE_IDENTIFICATION = 'MATH114'

--AND (SC4.FINAL_GRADE NOT LIKE '%T%' AND SC4.FINAL_GRADE NOT LIKE '%W%' AND SC4.FINAL_GRADE NOT LIKE '%N%' AND SC4.FINAL_GRADE NOT LIKE '%F%' 
--AND SC4.FINAL_GRADE NOT LIKE '%D%' AND SC4.FINAL_GRADE NOT LIKE '%C-%' AND SC4.FINAL_GRADE NOT LIKE '%P%')
--AND (SC4.FINAL_GRADE >= 'C' OR SC4.FINAL_GRADE >= '(2.0)')
--AND SC2.ACADEMIC_PERIOD >= '201835'
AND SC4.PERSON_UID = SC.PERSON_UID
AND SC4.FINAL_GRADE IS NOT NULL)) 

ORDER BY SC.NAME, SC.ID, SC.ACADEMIC_PERIOD
