SELECT 
COALESCE (spriden_id, ' ' ) AS spriden_id
, SPRIDEN_PIDM AS SPRIDEN_PIDM
, COALESCE (spriden_last_name||', '||spriden_first_name||' '||Spriden_mi, ' ' ) as name
, CASE WHEN WERSTFP_WSP IS NULL THEN ' ' ELSE CONVERT(WERSTFP_WSP,'US7ASCII') END AS WSP_DATE
,WERSTFP_FBI AS FBI_DATE

, COALESCE(WERSTFP_COMMENT, ' ') AS FP_COMMENTS

,WERSTFP_WA_ST_APP_EXP_DATE AS FBI_EXP_DATE
,WERSTFP_WA_ST_OPP_SENT_DATE as referral_date

,COALESCE (T.WESTB_MATH_HIGH, ' ' ) AS WESTB_MATH_HIGH
,COALESCE (T.WESTB_CR_HIGH, ' ' ) AS WESTB_CR_HIGH
,COALESCE (T.WESTB_CW_HIGH, ' ' ) AS WESTB_CW_HIGH
,T.WESTB_MATH_DATE
,T.WESTB_CR_DATE
,T.WESTB_CW_DATE

,COALESCE (T.SAT_MATH_HIGH, ' ' ) AS SAT_MATH_HIGH
,COALESCE (T.SAT_CR_HIGH, ' ' ) AS SAT_CR_HIGH
,COALESCE (T.SAT_CW_HIGH, ' ' ) AS SAT_CW_HIGH
, CASE WHEN T.SAT_MATH_DATE IS NULL THEN ' ' ELSE CONVERT(T.SAT_MATH_DATE,'US7ASCII') END AS SAT_MATH_DATE
,CASE WHEN T.SAT_CR_DATE IS NULL THEN ' ' ELSE CONVERT(T.SAT_CR_DATE,'US7ASCII') END AS SAT_CR_DATE
,CASE WHEN T.SAT_CW_DATE IS NULL THEN ' ' ELSE CONVERT(T.SAT_CW_DATE,'US7ASCII') END AS SAT_CW_DATE

,COALESCE (T.ACT_MATH_HIGH, ' ' ) AS ACT_MATH_HIGH
,COALESCE (T.ACT_CR_HIGH, ' ' ) AS ACT_CR_HIGH
,COALESCE (T.ACT_CW_HIGH, ' ' ) AS ACT_CW_HIGH
,CASE WHEN T.ACT_MATH_DATE IS NULL THEN ' ' ELSE CONVERT(T.ACT_MATH_DATE,'US7ASCII') END AS ACT_MATH_DATE
,CASE WHEN T.ACT_CR_DATE IS NULL THEN ' ' ELSE CONVERT(T.ACT_CR_DATE,'US7ASCII') END AS ACT_CR_DATE
,CASE WHEN T.ACT_CW_DATE IS NULL THEN ' ' ELSE CONVERT(T.ACT_CW_DATE,'US7ASCII') END AS ACT_CW_DATE

,COALESCE (APPL.WERAPPL_CURT_CODE, ' ' ) AS WERAPPL_CURT_CODE
,COALESCE (CUR.WEVCURT_DESC, ' ' ) AS GRADE_LEVEL
, CASE WHEN AACT.WERAACT_DATE IS NULL THEN ' ' ELSE CONVERT(AACT.WERAACT_DATE,'US7ASCII') END AS MATRIC_DATE
, COALESCE (CASE WHEN CONC IS NOT NULL AND MINR IS NOT NULL THEN MAJR||', '||CONC||', '||MINR
             WHEN CONC IS NOT NULL THEN MAJR||', '||CONC
             when minr is not null then majr||', '||minr else majr end, ' ' ) as program
from werstfp

JOIN SPRIDEN
ON SPRIDEN_PIDM = WERstfp_PIDM
AND SPRIDEN_CHANGE_IND IS NULL

LEFT JOIN ( SELECT SGBSTDN_PIDM, SGBSTDN_TERM_CODE_EFF, SGBSTDN_LEVL_CODE, SGBSTDN_PROGRAM_1,
           SGBSTDN_MAJR_CODE_1,SGBSTDN_MAJR_CODE_MINR_1, majr.stvmajr_desc as majr, conc.stvmajr_desc as conc, minr.stvmajr_desc as minr
           FROM SGBSTDN
           JOIN STVMAJR MAJR
                ON MAJR.STVMAJR_CODE =SGBSTDN_MAJR_CODE_1
                and majr.STVMAJR_VALID_MAJOR_IND = 'Y'
           LEFT JOIN STVMAJR CONC
                ON CONC.STVMAJR_CODE =SGBSTDN_MAJR_CODE_CONC_1
                AND conc.STVMAJR_VALID_CONCENTRATN_IND = 'Y'
           LEFT JOIN STVMAJR MINR
                ON MINR.STVMAJR_CODE =SGBSTDN_MAJR_CODE_MINR_1
                AND minr.STVMAJR_VALID_MINOR_IND = 'Y'
            where sgbstdn_pidm||sgbstdn_term_code_eff in 
             (SELECT sgbstdn_pidm||MAX(sgbstdn_term_code_eff) 
             FROM sgbstdn GROUP BY sgbstdn_pidm) )
  ON sgbstdn_pidm = werstfp_pidm
  
left JOIN wercert
ON WERCERT_PIDM = WERSTFP_PIDM

left JOIN werappl appl
ON APPL.WERAPPL_PIDM = WERSTFP_PIDM

LEFT JOIN WERAACT AACT
ON AACT.WERAACT_PIDM = APPL.WERAPPL_PIDM
and aact.weraact_code = 'MATR'

left JOIN wevcurt cur
on cur.wevcurt_code = appl.werappl_curt_code

LEFT JOIN stvmajr maj
on maj.stvmajr_code = SGBSTDN_MAJR_CODE_1

LEFT JOIN stvmajr min
ON MIN.stvmajr_code = SGBSTDN_MAJR_CODE_MINR_1

 left outer join
  ( --inline view for test scores
    select
      sortest_pidm,
      MAX(CASE WHEN SORTEST_TESC_CODE = 'S02' THEN SORTEST_TEST_SCORE ELSE NULL END) AS SAT_MATH_HIGH,
      MAX(CASE WHEN SORTEST_TESC_CODE = 'S01' THEN SORTEST_TEST_SCORE ELSE NULL END) AS SAT_CR_HIGH,
      MAX(CASE WHEN SORTEST_TESC_CODE = 'S07' THEN SORTEST_TEST_SCORE ELSE NULL END) AS SAT_CW_HIGH,
       MAX(CASE WHEN SORTEST_TESC_CODE = 'S02' THEN SORTEST_TEST_DATE ELSE NULL END) AS SAT_MATH_DATE,
      MAX(CASE WHEN SORTEST_TESC_CODE = 'S01' THEN SORTEST_TEST_DATE ELSE NULL END) AS SAT_CR_DATE,
      MAX(CASE WHEN SORTEST_TESC_CODE = 'S07' THEN SORTEST_TEST_DATE ELSE NULL END) AS SAT_CW_DATE,
     
      MAX(CASE WHEN SORTEST_TESC_CODE = 'A02' THEN SORTEST_TEST_SCORE ELSE NULL END) AS ACT_MATH_HIGH,
      MAX(CASE WHEN SORTEST_TESC_CODE = 'A03' THEN SORTEST_TEST_SCORE ELSE NULL END) AS ACT_CR_HIGH,
      MAX(CASE WHEN SORTEST_TESC_CODE IN ('A08','A32') THEN SORTEST_TEST_SCORE ELSE NULL END) AS ACT_CW_HIGH,
      MAX(CASE WHEN SORTEST_TESC_CODE = 'A02' THEN SORTEST_TEST_DATE ELSE NULL END) AS ACT_MATH_DATE,
      MAX(CASE WHEN SORTEST_TESC_CODE = 'A03' THEN SORTEST_TEST_DATE ELSE NULL END) AS ACT_CR_DATE,
      MAX(CASE WHEN SORTEST_TESC_CODE IN ('A08','A32') THEN SORTEST_TEST_DATE ELSE NULL END) AS ACT_CW_DATE,
     
      MAX(CASE WHEN SORTEST_TESC_CODE = 'WMAP' THEN SORTEST_TEST_SCORE ELSE NULL END) AS WESTB_MATH_HIGH,
      MAX(CASE WHEN SORTEST_TESC_CODE = 'WRDP' THEN SORTEST_TEST_SCORE ELSE NULL END) AS WESTB_CR_HIGH,
      MAX(CASE WHEN SORTEST_TESC_CODE = 'WWRP' THEN SORTEST_TEST_SCORE ELSE NULL END) AS WESTB_CW_HIGH,
      MAX(CASE WHEN SORTEST_TESC_CODE = 'WMAP' THEN SORTEST_TEST_DATE ELSE NULL END) AS WESTB_MATH_DATE,
      MAX(CASE WHEN SORTEST_TESC_CODE = 'WRDP' THEN SORTEST_TEST_DATE ELSE NULL END) AS WESTB_CR_DATE,
      MAX(CASE WHEN SORTEST_TESC_CODE = 'WWRP' THEN SORTEST_TEST_DATE ELSE NULL END) AS WESTB_CW_DATE   
    from sortest
    group by sortest_pidm
  ) T
  ON T.SORTEST_PIDM = WERSTFP_PIDM

where spriden_id = '00612444'

order by wercert_pidm
